namespace UserControlInItemsRepeaterTest
{
    [default_interface]
    runtimeclass SimpleUserControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        SimpleUserControl();
        String Data{ get; set; };
    }
}
